name: Health check
on:
  schedule:
    - cron: '45 18 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Url health check
        uses: Jtalk/url-health-check-action@v3.2
        with:
          url: https://pokedex-fullstack-11.onrender.com/health
          max-attempts: 4
          retry-delay: 55s
